### ISSUE TITLE
IfState is not cooperating 

### ISSUE THREAD

**Issue by jkCXf9X4** [jkCXf9X4/hass_script_engine#4]
its sending a function as id

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/script_engine/event/event_distributor.py", line 43, in pre_call
    callback(event=event_data)
  File "/config/custom_components/script_engine/decorator/to_state.py", line 49, in new_event
    self.decorators[0].default(*args, **kwargs)
  File "/config/custom_components/script_engine/decorator/if_state.py", line 45, in default
    update()
  File "/config/custom_components/script_engine/decorator/if_state.py", line 41, in update
    self.new_state = StateExt.get_state(self.hass, self.id).state
  File "/config/custom_components/script_engine/hass/extension/state.py", line 16, in get_state
    value = hass.states.get(entity_id)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1087, in get
    return self._states.get(entity_id.lower())

**Comment by jkCXf9X4** [comment]
handled in 0.5.0
